import { useEffect } from 'react';

export default function PrivacyPolicy() {
  useEffect(() => {
    document.title = "Privacy Policy | Selfera";
    const metaDescription = document.querySelector('meta[name="description"]');
    if (metaDescription) {
      metaDescription.setAttribute('content', 'Selfera Privacy Policy');
    }
  }, []);

  return (
    <div className="bg-surface min-h-screen">
      <section className="relative z-10 pt-32 pb-20 pl-4 sm:pl-8 md:pl-10 pr-6 sm:pr-12 md:pr-24 text-ink">
        <div className="mx-auto max-w-4xl w-full flex flex-col items-start text-left">
          <h1 className="text-4xl sm:text-5xl font-extrabold tracking-tightest text-ink mb-4">SELFERA PRIVACY POLICY</h1>
          <p className="text-ink-secondary font-medium mb-12">Effective Date: [To be added at launch]</p>
          <h2 className="text-2xl sm:text-3xl font-bold tracking-tight text-ink mt-16 mb-6">1. Who We Are</h2>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">This privacy policy sets out how Selfera Ltd ("Selfera", "we", "us", "our") collects, uses, and protects personal information when you visit selfera.co.uk or use our services.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Selfera Ltd is the data controller responsible for the personal information described in this policy.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Company details</h3>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Company name: Selfera Ltd</h3>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Registered office: [UK registered office to be added at registration]</h3>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Company registration number: [to be added at registration]</h3>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Trading website: selfera.co.uk</h3>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Pre-registration notice</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">selfera.co.uk is currently operated by Automaitee Digital pending UK registration of Selfera Ltd (expected October 2026). All enquiries submitted through this site are handled by Automaitee Digital until Selfera Ltd is registered. Once registration is complete, Selfera Ltd will assume responsibility as the data controller and this notice will be removed.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Contact us</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">For any questions about this privacy policy, to exercise your rights under UK data protection law, or to raise a concern about how we handle your personal information, please contact us at:</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5"><strong className="text-ink font-bold">Email:</strong> support@selfera.co.uk</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Please include "Privacy" in the subject line so we can route your query to our Privacy Lead promptly.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Privacy Lead</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Selfera has appointed a named Privacy Lead responsible for overseeing compliance with this policy and UK data protection law. The Privacy Lead can be contacted through support@selfera.co.uk.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Complaints to the Information Commissioner's Office</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">If you are unhappy with how we handle your personal data, we would like you to contact us first at support@selfera.co.uk so we can try to resolve the issue. You also have the right to lodge a complaint with the Information Commissioner's Office (ICO), the UK's data protection regulator, at any time.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5"><strong className="text-ink font-bold">Website:</strong> ico.org.uk</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5"><strong className="text-ink font-bold">Phone:</strong> 0303 123 1113</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5"><strong className="text-ink font-bold">Address:</strong> Wycliffe House, Water Lane, Wilmslow, Cheshire SK9 5AF</p>
          <h2 className="text-2xl sm:text-3xl font-bold tracking-tight text-ink mt-16 mb-6">2. What Personal Information We Collect</h2>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We collect personal information in several ways. Some information you give us directly, some we collect automatically when you use our website, and some we receive from third parties. This section explains what we collect in each situation.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We only collect personal information that we need. If a field is optional, you can leave it blank and we will still be able to help you.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Information You Provide Directly to Us</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">When you book a consultation with us, we collect your first and last name, email address, phone number, business name, business type or sector, website URL, number of employees, preferred consultation date and time, and any message you choose to share.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">When you contact us with a general enquiry, we collect your full name, business email address, company name, type of enquiry, WhatsApp number, phone number (optional), and your message.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">When you sign up for our newsletter or download content, we collect your full name and business email address. You can unsubscribe at any time by clicking the link at the bottom of any email we send, or by contacting us at support@selfera.co.uk.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">When you become a client, we collect your full name, email address, phone number, home or business address (for invoicing and identity verification), business registration details, VAT number if applicable, details of individuals in your team who will use our services, and signed contract information including the names of authorised signatories.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">While we work with you, we collect and retain records of our communications, which may include emails, WhatsApp messages, phone call records and notes, video call recordings where we have your consent, meeting notes, action items, and shared documents.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">When you make a payment, we use trusted third-party payment providers. We do not store your card details directly. Depending on the payment method you use, we will share the necessary information with Stripe for card payments or GoCardless for direct debit payments.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Information We Collect Automatically</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">When you visit selfera.co.uk, our website and hosting infrastructure automatically collect certain technical information. This includes your IP address, browser type and version, operating system, device type, the website you came from before visiting ours, pages you visit and how long you spend on each, and the date and time of your visit.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We currently use Google Analytics 4 to understand how visitors use our website and Meta Pixel to measure the effectiveness of any advertising we run on Facebook and Instagram. Both tools only load if you consent to them through our cookie banner.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Information We Collect from Third Parties</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We may receive information about you from referrals by existing clients, B2B lead generation platforms such as LinkedIn Sales Navigator, public business directories such as Companies House, and marketing partners that pass qualified leads to us.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Special Category Information</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Special category information includes information about health, biometric data, ethnicity, religion, sexual orientation, political opinions, trade union membership, and genetic data.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Selfera does not knowingly collect, process, or store special category information about you or any individual through our website or services.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">If a client engages us to work with data that includes special category information relating to their own customers, staff, or third parties, we will only process that information under the client's instructions and in accordance with a written agreement. In this situation, our client is the data controller and we act as a data processor.</p>
          <h2 className="text-2xl sm:text-3xl font-bold tracking-tight text-ink mt-16 mb-6">3. How We Collect Your Personal Information</h2>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We collect personal information through several channels. This section explains each of the ways your information reaches us.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Information You Provide Directly</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Through forms on our website, we collect personal information when you complete our consultation booking form, our general enquiries form, or any other form we may add for specific purposes.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">By email, you can contact us directly at support@selfera.co.uk. We receive your email address, any content in the email, attachments, and information visible in your email signature.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">By phone and WhatsApp, if you call our business number or send us a message on +44 7570546554, we receive your phone number, the content of your message, and any media you share. We do not record phone calls. We take manual notes of important calls and store these in our customer records. Messages sent through WhatsApp are routed through Meta's WhatsApp Business API infrastructure before they reach us.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">By post, you can write to us and we will retain the correspondence in our records. Postal address details will be added once Selfera Ltd's UK registered office is confirmed.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">In video calls with prospective clients, clients, and partners using Zoom, Google Meet, or Microsoft Teams, we may see and hear you and receive content you share on screen. We do not record video calls unless we ask for and receive your consent in advance.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">In person, we attend industry events, meetings, and consultations. Where we exchange business cards, collect contact details, or take notes during in-person conversations, we retain that information in our records.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Information We Collect Automatically When You Use Our Website</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Through cookies and similar technologies placed on your device, we and our approved third-party tools collect information about how you interact with our website. Automatic collection through these tools only takes place if you have given your consent through our cookie banner.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Through our website server and hosting infrastructure, our website is hosted by Vercel. Every visit to selfera.co.uk generates a server log entry that captures technical information about your visit. Server logs allow us to keep the website running, investigate errors, and protect against security threats.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Through our automation workflows, when you submit a form on our website, your submission may pass through automation workflows we use to route your information to the right place inside our systems.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Information We Receive from Third Parties</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">From referrals, an existing client, partner, or contact may pass your details to us as a recommendation. From B2B lead generation platforms such as LinkedIn Sales Navigator, we may identify prospective clients whose businesses match the sectors we serve. From public business directories such as Companies House, we may look up business information about you or your company. From marketing partners, we may receive information you agreed to share with them.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Information You Provide When You Become a Client</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Once you engage Selfera to deliver services, you will provide information directly during onboarding, through signed agreements, onboarding forms, calls, and emails. You may also enter information into our dashboard directly once your account is set up.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Combining Information from Different Sources</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We may combine information we receive from different channels to build an accurate picture of our relationship with you. For example, if you email us after submitting a form, we will link your email correspondence to your original form submission so we can respond in context.</p>
          <h2 className="text-2xl sm:text-3xl font-bold tracking-tight text-ink mt-16 mb-6">4. Why We Use Your Personal Information and the Legal Basis</h2>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We only use your personal information where the law allows us to. Under UK data protection law, we must have a valid legal basis for every use of your information.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Purposes and Legal Basis Summary</h3>
          <div className="overflow-x-auto my-8 border border-ink/10 rounded-2xl w-full">
<table className="w-full text-left border-collapse">
<thead className="bg-ink/5">
<tr><th className="px-6 py-4 text-sm font-bold text-ink border-b border-ink/10">Purpose</th><th className="px-6 py-4 text-sm font-bold text-ink border-b border-ink/10">Legal Basis</th></tr>
</thead>
<tbody className="divide-y divide-ink/10 bg-white">
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Responding to your consultation booking</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Contract preparation</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Responding to general enquiries</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Legitimate interests</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Sending newsletters and marketing content you have signed up for</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Consent</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Marketing our related services to existing clients</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Legitimate interests (soft opt-in, PECR)</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Contacting prospective clients we identify through third-party sources</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Legitimate interests</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Onboarding you as a client</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Contract performance</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Delivering the services you have engaged us for</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Contract performance</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Improving our products and services</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Legitimate interests</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Processing your payments</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Contract performance and legal obligation</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Keeping financial and tax records</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Legal obligation</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Running website analytics through Google Analytics 4</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Consent</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Measuring advertising through Meta Pixel</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Consent</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Operating our website securely and investigating errors</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Legitimate interests (recognised)</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Preventing and investigating fraud</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Legitimate interests and legal obligation</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Responding to legal requests</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Legal obligation</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Enforcing contracts and pursuing unpaid fees</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Legitimate interests</td></tr>
</tbody>
</table>
</div>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Detailed Explanation of Each Purpose</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">When you book a consultation, we use the information you provide to schedule the meeting, understand your business, and prepare for the call. This is a step you have asked us to take before we potentially enter into a contract with you.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">When you contact us with a general enquiry, we use your information to respond to your question. Responding to enquiries is a standard business activity we consider a legitimate interest. You can ask us to stop responding at any time.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We only send marketing emails and newsletters if you have specifically asked us to. When you sign up, we ask for your active consent through a clear opt-in. You can unsubscribe at any time.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">If you are already a client of ours, we may send you information about related services we think may be useful to your business. This is permitted under the "soft opt-in" rules in UK electronic marketing law. Every marketing message we send includes an easy way to unsubscribe.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We may identify potential clients through professional networking platforms, business directories, referrals, and similar sources. We contact you because your business matches the sectors we serve. This is our legitimate interest in growing our business. You have the right to object at any time.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Once you engage Selfera to deliver services, we collect and use the information needed to set up your account, prepare and sign your contract, and provide the services you have hired us for.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">While we deliver services under our contract, we use your information to run automations, provide dashboard access, communicate with your team, monitor performance, and everything else agreed in your contract.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We look at how our dashboard and services are used across our client base to improve them over time. Where possible, we use anonymised or aggregated information. Where we cannot fully anonymise, we rely on our legitimate interest in improving our products.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We use Stripe and GoCardless to process payments. We share the information they need to take payment from you. We keep records of payments as part of our contract with you and to meet our legal record-keeping duties.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">UK law requires us to keep financial records for a minimum period (currently six years under HMRC rules and the Companies Act).</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We use Google Analytics 4 to understand how visitors use our website and Meta Pixel to measure advertising campaigns. Both tools only load on your device if you have accepted the relevant cookies.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Our hosting provider Vercel automatically records server logs for every visit. We use these logs to keep the website running, detect and investigate security threats, and fix problems. UK data protection law specifically recognises this as a legitimate interest.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">If we identify suspicious activity, we may use your information to investigate and prevent fraud. This protects our business, our clients, and other users.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">If a court, regulator, or law enforcement agency asks us for information under valid legal authority, we may be required to provide it.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">If a client does not pay their invoices or breaches their contract with us, we may need to use their information to pursue the debt, take legal action, or resolve the dispute.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Choosing Not to Provide Information</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Where information is required to deliver a service or respond to your request, we will tell you at the point of collection. If you choose not to provide required information, we may not be able to help you. For everything else (optional fields, marketing preferences, cookies), you can choose not to provide the information and we will still work with you.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Changing Your Mind</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Where our processing relies on your consent, you can withdraw that consent at any time. This does not affect any processing that has already happened based on your earlier consent.</p>
          <h2 className="text-2xl sm:text-3xl font-bold tracking-tight text-ink mt-16 mb-6">5. Who We Share Your Personal Information With</h2>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We do not sell your personal information. We only share it in the specific circumstances set out below.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Where we share your information with a third party, we take steps to ensure they treat it with the same standards we do. This includes putting written data processing agreements in place and choosing providers who meet appropriate security and privacy standards.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Our Service Providers (Sub-Processors)</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We work with a small number of trusted service providers who process personal information on our behalf under our instructions. Each provider is bound by a written data processing agreement.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We keep an up-to-date list of our sub-processors on our website. You can view the current list at selfera.co.uk/sub-processors.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">The categories of sub-processors we currently use include website hosting and infrastructure, database and storage, business communications and productivity, payment processing, marketing and analytics platforms, AI service providers, and business platform APIs.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Advance Notice of Changes to Sub-Processors</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">When we add a new sub-processor, we will update our published sub-processor list at least 30 days before the change takes effect. Existing clients can request to be notified of updates by emailing support@selfera.co.uk.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Our Team and Contractors</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Members of our team and our contractors access personal information only where necessary to do their work. Everyone who accesses personal information on our behalf is bound by written confidentiality obligations and trained on data protection.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Professional Advisors</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We may share your information with our professional advisors where necessary. These include our accountants for tax and financial record-keeping, our legal advisors for advice or in the event of a dispute, and our insurers for insurance purposes and in the event of a claim. Each of these advisors acts as an independent data controller and is bound by their own professional confidentiality duties.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Public Authorities and Legal Requirements</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We may share your information with courts, regulators, tax authorities, and law enforcement agencies where we are required by law to do so, or where we believe in good faith that sharing is necessary to comply with a legal obligation, protect someone's safety, or defend our legal rights.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Business Transfers</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">If Selfera is ever sold, merged, restructured, or has any part of its business or assets transferred to another organisation, your personal information may be transferred as part of that transaction. If this happens, we will let you know in advance where possible, and the new owner will be bound by the same protections set out in this policy.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">International Transfers</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Some of our service providers and members of our team are located outside the United Kingdom. When your personal information is transferred outside the UK, we take steps to ensure it is protected to UK standards. Full details of how we handle international transfers are set out in the International Transfers section of this policy.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Where Selfera Acts as a Processor for Our Clients</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">When we deliver services to a client, we sometimes handle personal information belonging to the client's own customers, staff, or contacts. In those situations, our client is the data controller and Selfera is a data processor acting under the client's instructions. We do not use that information for our own purposes.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">If you are a customer, employee, or contact of one of our clients and you want to exercise your rights in relation to the information they hold about you, you should contact the client directly. We will support them in responding to your request as required by our agreement with them.</p>
          <h2 className="text-2xl sm:text-3xl font-bold tracking-tight text-ink mt-16 mb-6">6. International Transfers of Your Personal Information</h2>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Selfera is a UK company, but some of the service providers we work with and members of our team are located outside the United Kingdom. This means your personal information may be transferred to countries outside the UK.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Whenever we transfer your information outside the UK, we take the steps required by UK data protection law to ensure it continues to be protected to the same standard.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Where Your Information Goes</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Within the United Kingdom, some of our providers and operations are based in the UK. No international transfer applies to these.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Within the European Union, some of our hosting and database infrastructure is located in the EU. The UK has recognised the EU as providing an adequate level of protection for personal data, so these transfers do not require additional safeguards.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">To the United States, several of our providers are based in the United States. Transfers to these providers are protected either by the UK-US Data Bridge where the provider is certified, or by the UK International Data Transfer Agreement or Standard Contractual Clauses with the UK Addendum where the provider is not certified.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">To India, our subsidiary Selfera India Pvt Ltd, which handles technology and operations work, is based in India. India does not have a UK adequacy decision, so all transfers of personal information from Selfera UK Ltd to Selfera India Pvt Ltd are governed by a signed UK International Data Transfer Agreement.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">In addition, we have completed a Transfer Impact Assessment to identify any risks specific to India and implemented additional technical safeguards including encryption in transit, encryption at rest for sensitive data, and access controls.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Selfera India Pvt Ltd</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Selfera India Pvt Ltd is a wholly-owned subsidiary of Selfera UK Ltd. It handles all technology, engineering, and operational delivery work for Selfera globally. Where our India team members access UK client data, it is only to deliver the services our UK clients have engaged us for.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Access from India is governed by the same IDTA and internal safeguards that apply to all our data transfers. All Selfera India team members are bound by written confidentiality obligations, receive data protection training, and can only access what they need for their specific role.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Occasional Support Access</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Where our India team needs to provide urgent technical support, troubleshoot an issue, or respond to a security incident affecting UK client data, that access is still governed by the IDTA and our internal safeguards. We do not grant any team member access to UK personal data outside these controls.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Onward Transfers</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Some of our sub-processors may engage their own service providers to help deliver their services to us. Where this happens, our sub-processors are contractually required to ensure equivalent safeguards apply to any onward transfer of your information.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Notification of Changes</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">When we add a new international transfer destination or change the safeguards we rely on, we update our sub-processor list at selfera.co.uk/sub-processors at least 30 days before the change takes effect.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Your Rights Wherever Your Data Is</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Wherever your personal information is processed, your rights under UK data protection law continue to apply. You can exercise your rights by contacting us at support@selfera.co.uk.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Copies of Our Safeguards</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">You have the right to request a copy of the safeguards we rely on for international transfers. To request a copy, email support@selfera.co.uk with "Transfer safeguards request" in the subject line.</p>
          <h2 className="text-2xl sm:text-3xl font-bold tracking-tight text-ink mt-16 mb-6">7. How Long We Keep Your Personal Information</h2>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We keep your personal information only for as long as we need it for the purposes we collected it for. When we no longer need it, we delete it or anonymise it so it can no longer identify you.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">For some categories of information, UK law requires us to keep records for a minimum period. Where legal retention obligations apply, we keep the information for that period even if you ask us to delete it earlier.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Retention Periods by Category</h3>
          <div className="overflow-x-auto my-8 border border-ink/10 rounded-2xl w-full">
<table className="w-full text-left border-collapse">
<thead className="bg-ink/5">
<tr><th className="px-6 py-4 text-sm font-bold text-ink border-b border-ink/10">Category</th><th className="px-6 py-4 text-sm font-bold text-ink border-b border-ink/10">Retention Period</th></tr>
</thead>
<tbody className="divide-y divide-ink/10 bg-white">
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Website server logs and technical data</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">90 days</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Website analytics data (Google Analytics 4)</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">14 months</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Cookies</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Set individually per cookie</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Consultation booking data (non-client)</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">24 months from booking date</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">General enquiries data (non-client)</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">24 months from enquiry date</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Newsletter subscribers (active)</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">For as long as you remain subscribed</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Newsletter unsubscribers</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Email only on suppression list</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Video call recordings</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">12 months from date of call</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Client contract records (during engagement)</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Duration of engagement</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Client contract records (after engagement)</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">6 years from end of engagement</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Financial records, invoices, tax records</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">6 years (HMRC requirement)</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Email correspondence</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">6 years</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">WhatsApp business messages</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">6 years</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Marketing engagement data</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Duration of subscription plus 6 months</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Employment records</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">6 years after employment ends</td></tr>
<tr className="hover:bg-ink/[0.02] transition-colors"><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">Cookie consent records</td><td className="px-6 py-4 text-sm font-medium text-ink-secondary w-1/2">12 months from date of consent</td></tr>
</tbody>
</table>
</div>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Data Held Solely to Meet Legal Obligations</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Where we keep information only because the law requires us to (for example, invoices kept to meet HMRC record-keeping duties), we restrict access to that information to authorised personnel. It is not used for any other purpose.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Backups</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">For a short period after we delete your personal information from our live systems, a copy may remain in our secure backup systems. This copy is protected by the same security controls as our live systems, is not accessed for any operational purpose, and is deleted within 90 days as our backup cycles complete.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Automatic Deletion</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Our systems are designed to automatically delete or anonymise personal information at the end of its retention period. Where automatic deletion is not technically possible, we conduct regular reviews and delete manually.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Requests to Delete Your Information Sooner</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">You have the right to ask us to delete your personal information before the retention period ends. If any of your information is legally required to be retained (for example, invoices under HMRC rules), we cannot delete it before the legal retention period expires. Where this is the case, we will anonymise the information where possible, delete everything not required by law, continue to keep only the minimum information required by law until the retention period ends, and delete it as soon as the retention period expires.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We will always explain to you what we can and cannot delete when we respond to your request.</p>
          <h2 className="text-2xl sm:text-3xl font-bold tracking-tight text-ink mt-16 mb-6">8. Your Rights Over Your Personal Information</h2>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">UK data protection law gives you a number of rights over your personal information. This section explains what those rights are, when they apply, and how to exercise them.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">The Rights You Have</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5"><strong className="text-ink font-bold">The right to be informed:</strong> You have the right to know how we use your personal information. That is exactly what this privacy policy is for.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5"><strong className="text-ink font-bold">The right of access:</strong> You have the right to ask for a copy of the personal information we hold about you, along with information about how we use it. This is known as a Subject Access Request.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5"><strong className="text-ink font-bold">The right to rectification:</strong> If any of your personal information is inaccurate or incomplete, you can ask us to correct it or fill in the missing details.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5"><strong className="text-ink font-bold">The right to erasure:</strong> You can ask us to delete your personal information. This is sometimes called the "right to be forgotten". Where UK law requires us to keep certain information, we cannot delete it until the legal retention period ends. We will explain what we can and cannot delete.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5"><strong className="text-ink font-bold">The right to restrict processing:</strong> You can ask us to pause our processing of your personal information in certain situations, for example while a dispute or correction is being resolved.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5"><strong className="text-ink font-bold">The right to data portability:</strong> For information you have provided to us directly, and where we process it based on your consent or a contract with you, you have the right to receive that information in a machine-readable format (JSON or CSV) so you can move it to another service.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5"><strong className="text-ink font-bold">The right to object:</strong> You can object to our use of your personal information where we rely on legitimate interests. You can also object to direct marketing at any time, and we will stop immediately. Your email address will remain on our suppression list only, to make sure we never contact you again by accident.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Rights related to automated decision-making: Selfera does not make any decisions about you based solely on automated processing. Every significant decision that could affect you involves a human review by our team.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5"><strong className="text-ink font-bold">The right to withdraw consent:</strong> Where we process your personal information based on your consent, you can withdraw your consent at any time. Withdrawing consent does not affect any processing we carried out before you withdrew it.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5"><strong className="text-ink font-bold">The right to complain to the Information Commissioner's Office:</strong> If you are unhappy with how we handle your personal information, we would like you to contact us first at support@selfera.co.uk so we can try to resolve the issue. You also have the right to lodge a complaint with the ICO at any time.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">ICO contact details:</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5"><strong className="text-ink font-bold">Website:</strong> ico.org.uk</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5"><strong className="text-ink font-bold">Phone:</strong> 0303 123 1113</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5"><strong className="text-ink font-bold">Address:</strong> Wycliffe House, Water Lane, Wilmslow, Cheshire SK9 5AF</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">How to Exercise Your Rights</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">To exercise any of your rights, contact us at support@selfera.co.uk with "Rights Request" in the subject line. Please tell us which right you want to exercise, what personal information the request relates to, and any relevant context that will help us action your request quickly.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We may need to verify your identity before we can act on your request. For sensitive requests such as access, deletion, or portability, we may ask for proof of identity such as a photograph of a government-issued ID, or we may ask you to verify from an email address we already have on record.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">If someone is making a request on your behalf, we will need to see valid written authorisation before we can act.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Response Format</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We will respond to your Subject Access Request or portability request in the format you prefer where possible. Standard options are JSON (machine-readable, technical), CSV (spreadsheet-friendly), or PDF (human-readable). If you have a preference, please let us know when you make your request.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">How Long We Take to Respond</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We will respond to your rights request within one month of receiving it. In some cases, if your request is particularly complex or you have made several requests, we may need up to two additional months. If this happens, we will let you know within the first month and explain why.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Cost</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Exercising your rights is normally free of charge. In limited circumstances, such as where a request is clearly excessive, we may charge a reasonable fee to cover our administrative costs, or we may refuse to act on the request. If this applies, we will explain why and set out any fee before proceeding.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Where We Cannot Fully Action Your Request</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">There are some situations where we may not be able to fully action your request. These include where UK law requires us to keep certain information, where the information is needed to defend legal claims, or where the request would infringe the rights of another person. Where this applies, we will explain what we can and cannot do, and we will always help you understand your remaining options, including your right to complain to the ICO.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Special Note on AI and Automation</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Because AI is central to how we deliver our services, we understand you may have specific questions about how automation affects your personal information. You have the right to ask what AI systems have processed your information, what outputs, decisions, or profiles have been generated, and whether any of that information is used to improve our services in future.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We will respond openly and fully. Where we use AI to help us work more efficiently, a human always makes the final decision on anything that affects you.</p>
          <h2 className="text-2xl sm:text-3xl font-bold tracking-tight text-ink mt-16 mb-6">9. Cookies and Similar Technologies</h2>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Our website uses cookies and similar storage technologies to help our site work, to understand how visitors use it, and where you consent, to measure the effectiveness of any advertising we run.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">This section gives you a summary of how we use cookies. Our full Cookie Policy is available at selfera.co.uk/cookie-policy, where you can also see the full list of cookies we use.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">What Cookies Are</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Cookies are small text files that a website places on your device when you visit. They allow the website to remember information about your visit, such as your preferences or actions. We also use similar technologies including local storage, session storage, and web beacons.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Categories of Cookies We Use</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Strictly necessary cookies are essential for our website to work. They enable core functions like session management and security. These cookies do not require your consent and cannot be turned off.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Analytics cookies help us understand how visitors use our website. We use Google Analytics 4 for this purpose, with IP anonymisation enabled so we cannot identify individual visitors from analytics data alone. These cookies only load if you accept them.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Marketing cookies are used to measure the effectiveness of advertising we run on other platforms and to help those platforms show relevant content. We use Meta Pixel, LinkedIn Insight Tag, and Google Ads conversion tracking for this purpose. These cookies may follow you to other websites after you leave ours. These cookies only load if you accept them.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Your Cookie Choices</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">When you first visit our website, our cookie banner asks for your consent before any non-essential cookies are placed. You can Accept all cookies, Reject all non-essential cookies, or Customise your choices by turning specific categories on or off.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Rejecting non-essential cookies does not affect your ability to use our website.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Changing Your Cookie Choices</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">You can change your cookie preferences at any time by clicking the "Cookie preferences" link in the footer of any page. You can also delete cookies at any time through your browser settings.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">How Long Cookies Last</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Different cookies last for different periods, from the length of a single visit to up to 12 months. Your cookie consent choice is remembered for 12 months. After that, we will ask again.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Consent Records</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">When you give or update your cookie consent, we record the choice you made, when you made it, and the version of our cookie policy at that time. We keep these records for 12 months.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Third-Party Tracking</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Some of the cookies we use (marketing cookies) are placed by third parties such as Meta, Google, and LinkedIn. These providers may use the data they collect through our website to build profiles of your interests and show you relevant content on their own platforms and other websites.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">To learn more, please see their own privacy policies at policies.google.com/privacy, meta.com/privacy, and linkedin.com/legal/privacy-policy.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Server-Side Tracking</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We do not currently use server-side tracking. All tracking currently happens through cookies loaded in your browser, and only with your consent.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Do Not Track Signals</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Our website does not currently respond automatically to Do Not Track signals. However, you can achieve the same effect by rejecting non-essential cookies through our cookie banner.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Changes to How Cookies Work</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">The way websites use cookies is changing. As these changes take effect, we may update the cookies we use and how they work. We will update this section and our Cookie Policy to reflect any material changes.</p>
          <h2 className="text-2xl sm:text-3xl font-bold tracking-tight text-ink mt-16 mb-6">10. How We Keep Your Personal Information Safe</h2>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Protecting your personal information is a core part of how we operate. This section explains the measures we take to keep your information safe from unauthorised access, loss, misuse, or accidental disclosure.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Technical Measures</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We use encryption in transit so all data moving between your device, our website, and our systems is protected using industry-standard encryption protocols. We use encryption at rest so sensitive information stored in our systems is protected. We use role-based access controls so only authorised team members can access personal information. Every member of our team accessing Selfera systems must use two-factor authentication to sign in. We use a dedicated password management tool to store credentials securely.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Each of our clients has their own separate infrastructure. One client's data is never stored alongside another client's data. This means there is no risk of one client accidentally seeing another client's information.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We take encrypted backups regularly and test that we can restore from them. Our website is protected by a web application firewall and rate limiting. We monitor for known vulnerabilities and apply security updates promptly.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Organisational Measures</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We have documented data protection, HR, and project management policies that apply to everyone in our team. Every team member and contractor signs a written agreement with confidentiality obligations before they access any personal information. Everyone in our team completes data protection and security training as part of onboarding and refresher training every year.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Team members only access the information they need for their specific role, and access is reviewed regularly. Before we engage any service provider that will process personal information on our behalf, we assess their security posture and put a written data processing agreement in place. We have a documented plan for responding to security incidents. We review our security measures at least annually and after any material change to our systems or services.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Physical Measures</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Our office is secured with controlled access and clean-desk practices are followed for sensitive documents. Workstations are encrypted and hardware is securely disposed of at the end of its life.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Responsible Disclosure</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">If you are a security researcher and you believe you have found a security issue affecting Selfera, please contact us at support@selfera.co.uk with "Security Report" in the subject line.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">If you follow our responsible disclosure process, we will acknowledge your report within 5 working days, keep you informed as we investigate and fix the issue, credit you for your finding if you would like us to, and not pursue any legal action against you for good-faith research conducted under these terms.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We do not currently offer paid rewards for security reports.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">In the Event of a Personal Data Breach</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">If a personal data breach happens and is likely to result in a risk to individuals, we will notify the Information Commissioner's Office within the required 72-hour period.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">If a personal data breach is likely to result in a high risk to your rights and freedoms, we will notify you without undue delay so you can take steps to protect yourself. We will explain what happened, what information was affected, what we are doing about it, and what you can do to protect yourself.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We keep an internal log of all personal data breaches, including those that do not require notification, so we can learn from every incident and prevent recurrence.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">No System Is Perfect</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">No security measures can guarantee complete safety. What we can promise is that we take security seriously, we invest in it continuously, and we will always be honest with you if something goes wrong.</p>
          <h2 className="text-2xl sm:text-3xl font-bold tracking-tight text-ink mt-16 mb-6">11. Children's Personal Information</h2>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Selfera provides services to business owners and professionals. Our website and services are not intended for anyone under the age of 18, and we do not knowingly collect personal information from children.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Age Threshold</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">You must be 18 years or over to use Selfera's services as a client, sign up for our newsletter or download our content, apply for a role at Selfera, or book a consultation with us. When you sign up for our newsletter, we ask you to confirm that you are 18 or over before we accept your signup.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">If a Child Provides Us with Personal Information</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">If we discover that we have collected personal information from a child, we will delete the information as soon as possible, notify a parent or guardian where we have their contact details, and log the incident in our internal records to review our processes.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">If you believe a child has provided personal information to us, please contact us at support@selfera.co.uk with "Child's information" in the subject line, and we will action your request without needing you to prove parental responsibility.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">When Selfera Processes Client Data That May Include Children's Information</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Some of the sectors we work with (such as Beauty and Selfcare, Training Studios, and Fashion Boutiques) may have customers who are children. When we deliver services to those clients, our client is the data controller and Selfera is a data processor.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Where children's information may be involved, we work with our clients to make sure additional safeguards are applied. This includes restricted access controls, extra caution in how we design automations that touch children's information, and where required, a Data Protection Impact Assessment before we start work.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">If you are a customer of a Selfera client and have concerns about how your child's information is being handled, please contact the client directly. We will support them in responding to your concern.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Services Primarily Aimed at Children</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Where Selfera is asked to work with a client whose services are primarily aimed at children (such as schools, tutoring services, children's health services, or children's clothing brands), we treat this as a heightened engagement.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Before starting work, we complete a Data Protection Impact Assessment, review the additional legal obligations that apply, and put appropriate additional safeguards in place. We reserve the right to decline engagements where we cannot meet the required standards.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Age Appropriate Design Code</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">The UK's Age Appropriate Design Code sets specific standards for online services that are likely to be accessed by children. While our own services are not designed for children, we take the Code's principles into consideration wherever they may apply.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Marketing and Children</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We do not send marketing communications to anyone we know to be under 18. If we discover we have added a minor to any marketing list, we will remove them immediately, add their contact details to our suppression list, and review how they were added.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Reporting Concerns</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">If you have any concerns about children's information in connection with Selfera, please contact us at support@selfera.co.uk with "Children's data concern" in the subject line. We will treat your concern with priority and respond as quickly as we can.</p>
          <h2 className="text-2xl sm:text-3xl font-bold tracking-tight text-ink mt-16 mb-6">12. Changes to This Privacy Policy</h2>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">This privacy policy may change from time to time. This section explains when and how we make changes, what counts as a material change, and how we let you know.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">When We Update This Policy</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We review this privacy policy regularly and update it whenever we need to. Common reasons for updates include changes to how we collect or use personal information, changes to our sub-processors or international transfers, changes to UK data protection law or ICO guidance, adding new services, features, or products, clarifications or improvements to make the policy easier to understand, and corrections of typos or minor language improvements.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Material Changes and Non-Material Changes</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We treat some changes as material and some as non-material.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Material changes are those that affect how we handle your personal information in a substantive way. Examples include adding a new purpose for using your information, adding a new legal basis, adding a new category of information we collect, adding a new type of provider we share information with, adding a new country your information may be transferred to, changing how long we keep your information, or changing how you can exercise your rights.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Non-material changes are updates that do not affect how we handle your personal information. Examples include fixing typos or grammatical errors, improving the clarity of the language without changing meaning, updating contact details, or updating the version number.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">How We Notify You of Material Changes</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">When we make a material change to this policy, we will send an email notification to all clients and newsletter subscribers at least 30 days before the change takes effect, display a clear banner on selfera.co.uk for at least 30 days before and after the change, and update the effective date at the top of this policy.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">You will have at least 30 days to review the change before it comes into force.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Non-Material Changes</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We may make non-material changes at any time without notice. When you continue using our website or services after a non-material change, you agree to those updates.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Emergency Updates for Legal or Security Reasons</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">In some situations, we may need to update this policy immediately without the standard 30-day notice period. This applies when the update is required by law or by a change in regulation, when the update is needed to respond to a security incident or vulnerability, or when the update is needed to protect the safety of individuals.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">When we make an emergency update, we will notify you within 7 days after the change and explain the reason.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Your Options If You Disagree with a Material Change</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">If you disagree with a material change to this policy, you have the right to end your relationship with Selfera.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">For clients, this means terminating your service agreement (subject to any notice periods in your contract). We will delete or return your personal information according to our retention rules and our contract with you.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">For newsletter subscribers, you can unsubscribe at any time using the link in any email or by contacting us at support@selfera.co.uk.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">For website visitors, you can stop using our website.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Previous Versions of This Policy</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We keep an archive of previous versions of this privacy policy so you can see what has changed over time. Previous versions are available at selfera.co.uk/privacy-policy/archive. Each version is dated so you can see when it was in effect.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Effect on Existing Client Agreements</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">If you are a client of Selfera and have a signed service agreement with us, that agreement may contain specific terms about how we handle your data. Where a specific term in your service agreement conflicts with this general privacy policy, the specific term in your service agreement applies to the personal information covered by that agreement.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">This general privacy policy continues to apply to all other personal information we handle, including personal information about you as a website visitor and personal information about people who are not covered by a specific client agreement.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">The Latest Version</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">You can always find the current version of this policy at selfera.co.uk/privacy-policy. The effective date shown at the top of the policy tells you when the current version came into force.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">If you are unsure whether you are looking at the current version, please contact us at support@selfera.co.uk.</p>
          <h2 className="text-2xl sm:text-3xl font-bold tracking-tight text-ink mt-16 mb-6">13. Contact and Complaints</h2>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">If you have any questions about this privacy policy, want to exercise your rights under UK data protection law, or want to raise a concern about how we handle your personal information, this section explains how to reach us and what to expect.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">How to Contact Us</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">By email: The best way to reach us is by email at support@selfera.co.uk. Please include a clear subject line so we can route your query to the right person quickly. Suggested subject lines include Privacy question, Rights request, Complaint, Security report, or Child's information.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">By WhatsApp: You can also reach us on WhatsApp at +44 7570546554. WhatsApp is monitored during normal business hours.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">By post: Postal address details will be added once Selfera Ltd's UK registered office is confirmed.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">What to Expect When You Contact Us</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We aim to respond to general privacy queries within 10 working days.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">For rights requests (Subject Access Requests, deletion requests, and similar), we respond within one month as required by law. If your request is complex, we may extend this by up to two additional months and will let you know within the first month.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">For urgent security or safeguarding concerns, we respond as quickly as we can. If you flag something as urgent, please tell us why so we can prioritise it correctly.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Sensitive Contact Requests</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">If you are in a sensitive or vulnerable situation and need to contact us with particular discretion (for example, if you are concerned about someone else seeing your communication with us), please let us know. We will handle your request with additional care and can arrange alternative communication methods where appropriate.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">If You Contact the Wrong Address</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">If you send a privacy-related query to any Selfera email address, including sales, marketing, or general enquiries, it will be routed internally to our Privacy Lead. You do not need to know the correct address in advance. That said, using support@selfera.co.uk with a clear subject line helps us respond faster.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Making a Complaint</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">If you are unhappy with something we have done, or something we have not done, and you would like us to look into it as a complaint, please contact us at support@selfera.co.uk with "Complaint" in the subject line.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">When we receive your complaint, we will acknowledge your complaint in writing within 5 working days, investigate what happened, give you a full written response within 30 days, and explain what we have done and, if we have got something wrong, what we are doing to put it right.</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">If your complaint is complex and needs longer to investigate, we will let you know before the 30 days are up and explain how long it will take.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">If You Are Not Satisfied</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">If you are not satisfied with our response to your complaint, or you would prefer not to complain to us directly, you have the right to lodge a complaint with the Information Commissioner's Office (ICO), the UK's data protection regulator.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">The ICO's contact details are:</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5"><strong className="text-ink font-bold">Website:</strong> ico.org.uk</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5"><strong className="text-ink font-bold">Phone:</strong> 0303 123 1113</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5"><strong className="text-ink font-bold">Address:</strong> Wycliffe House, Water Lane, Wilmslow, Cheshire SK9 5AF</p>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">You can complain to the ICO at any time, whether or not you have raised the issue with us first. We would appreciate the opportunity to try to resolve your concern before you go to the ICO, but this is entirely your choice.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Language</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">We respond to queries and complaints in English. If you would prefer to communicate in another language, please let us know and we will do our best to arrange translation.</p>
          <h3 className="text-xl font-bold tracking-tight text-brand-blue mt-10 mb-4">Keeping in Touch</h3>
          <p className="text-base leading-relaxed text-ink-secondary font-medium mb-5">Once we have responded to your query or complaint, we may follow up to check that you are satisfied with the outcome. If you would prefer not to be contacted again, please tell us and we will respect that.</p>
        </div>
      </section>
    </div>
  );
}
